"""
User service — get-or-create pattern.

Always returns a valid User, creating one with default values if
the phone number is not yet registered.

Returns a tuple (user, is_new) so the caller can trigger onboarding
flows for first-time users.
"""

import logging

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.user import User, _generate_public_id

logger = logging.getLogger(__name__)


async def get_or_create_usuario(
    telefono: str, db: AsyncSession
) -> tuple[User, bool]:
    """
    Look up a user by phone number. If not found, create one with
    sensible defaults and return it.

    This function NEVER raises for a missing user — it auto-creates.

    Parameters
    ----------
    telefono : str
        The unique phone number (e.g. "+5491122334455").
    db : AsyncSession
        The async SQLAlchemy session.

    Returns
    -------
    tuple[User, bool]
        (user, is_new) — ``is_new`` is True when the user was just created.
    """
    stmt = select(User).where(User.telefono == telefono)
    result = await db.execute(stmt)
    user = result.scalar_one_or_none()

    if user is not None:
        # ── Backfill public_id for pre-existing users ───────────
        if not user.public_id:
            user.public_id = _generate_public_id()
            await db.commit()
            await db.refresh(user)
            logger.info(
                "Backfilled public_id=%s for user id=%d",
                user.public_id,
                user.id,
            )

        logger.info("User found: id=%d telefono=%s", user.id, telefono)
        return user, False

    # Auto-create with defaults (public_id generated by column default)
    user = User(
        nombre="Usuario",
        apellido="WhatsApp",
        telefono=telefono,
        moneda_principal="ARS",
    )
    db.add(user)
    await db.commit()
    await db.refresh(user)

    logger.info(
        "User created: id=%d telefono=%s public_id=%s",
        user.id,
        telefono,
        user.public_id,
    )
    return user, True
